### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by acidjunk** [acidjunk/shop-backend#1]
- [ ] Determine if we want: `ProductTable` or `Product` and refactor accordingly
- [ ] How to model the translations fields in a generic way
- [ ] How to create: admin and customer api endpoints without schema and crud duplication
